import Foundation

struct InsightsBadge: Identifiable {
    let id: String
    let title: String
    let requirement: String
    let icon: String
    let unlocked: Bool
    let progress: String
}

extension InsightsSnapshot {
    var badges: [InsightsBadge] {
        let total = totalDuration / 3600
        return [
            .init(id: "first", title: String(localized: "First session", bundle: .app), requirement: String(localized: "Complete your first session", bundle: .app), icon: "flag.fill", unlocked: total > 0, progress: String(localized: "\(sessionCount) sessions", bundle: .app)),
            .init(id: "ten", title: String(localized: "10-hour club", bundle: .app), requirement: String(localized: "Work 10 total hours", bundle: .app), icon: "clock.fill", unlocked: total >= 10, progress: progressText(DurationText.compact(total * 3600), String(localized: "10h", bundle: .app))),
            .init(id: "fifty", title: String(localized: "Half-century", bundle: .app), requirement: String(localized: "Work 50 total hours", bundle: .app), icon: "flame.fill", unlocked: total >= 50, progress: progressText(DurationText.compact(total * 3600), String(localized: "50h", bundle: .app))),
            .init(id: "hundred", title: String(localized: "Century", bundle: .app), requirement: String(localized: "Work 100 total hours", bundle: .app), icon: "bolt.fill", unlocked: total >= 100, progress: progressText(DurationText.compact(total * 3600), String(localized: "100h", bundle: .app))),
            .init(id: "quarter", title: String(localized: "Quarter kilo", bundle: .app), requirement: String(localized: "Work 250 total hours", bundle: .app), icon: "crown.fill", unlocked: total >= 250, progress: progressText(DurationText.compact(total * 3600), String(localized: "250h", bundle: .app))),
            .init(id: "fivehundred", title: String(localized: "Half-thousand", bundle: .app), requirement: String(localized: "Work 500 total hours", bundle: .app), icon: "crown.fill", unlocked: total >= 500, progress: progressText(DurationText.compact(total * 3600), String(localized: "500h", bundle: .app))),
            .init(id: "sevenfifty", title: String(localized: "Three-quarter legend", bundle: .app), requirement: String(localized: "Work 750 total hours", bundle: .app), icon: "medal.fill", unlocked: total >= 750, progress: progressText(DurationText.compact(total * 3600), String(localized: "750h", bundle: .app))),
            .init(id: "thousand", title: String(localized: "Thousand-hour", bundle: .app), requirement: String(localized: "Work 1,000 total hours", bundle: .app), icon: "trophy.fill", unlocked: total >= 1_000, progress: progressText(DurationText.compact(total * 3600), String(localized: "1,000h", bundle: .app))),
            .init(id: "titan", title: String(localized: "Time titan", bundle: .app), requirement: String(localized: "Work 1,500 total hours", bundle: .app), icon: "diamond.fill", unlocked: total >= 1_500, progress: progressText(DurationText.compact(total * 3600), String(localized: "1,500h", bundle: .app))),
            .init(id: "streak", title: String(localized: "On a roll", bundle: .app), requirement: String(localized: "Keep a 3-day streak", bundle: .app), icon: "flame.circle.fill", unlocked: currentStreak >= 3, progress: progressText(String(currentStreak), String(localized: "3 days", bundle: .app))),
            .init(id: "weekstreak", title: String(localized: "Weekly fire", bundle: .app), requirement: String(localized: "Keep a 7-day streak", bundle: .app), icon: "calendar.badge.clock", unlocked: currentStreak >= 7, progress: progressText(String(currentStreak), String(localized: "7 days", bundle: .app))),
            .init(id: "monthstreak", title: String(localized: "Unstoppable", bundle: .app), requirement: String(localized: "Keep a 30-day streak", bundle: .app), icon: "infinity", unlocked: currentStreak >= 30, progress: progressText(String(currentStreak), String(localized: "30 days", bundle: .app))),
            .init(id: "streak14", title: String(localized: "Fortnight fire", bundle: .app), requirement: String(localized: "Reach a 14-day streak", bundle: .app), icon: "sparkles", unlocked: longestStreak >= 14, progress: progressText(String(longestStreak), String(localized: "14 days", bundle: .app))),
            .init(id: "streak60", title: String(localized: "Seasoned", bundle: .app), requirement: String(localized: "Reach a 60-day streak", bundle: .app), icon: "mountain.2.fill", unlocked: longestStreak >= 60, progress: progressText(String(longestStreak), String(localized: "60 days", bundle: .app))),
            .init(id: "week", title: String(localized: "Weekly finisher", bundle: .app), requirement: String(localized: "Log 7 sessions", bundle: .app), icon: "calendar.badge.plus", unlocked: sessionCount >= 7, progress: progressText(String(sessionCount), String(localized: "7 sessions", bundle: .app))),
            .init(id: "sessions25", title: String(localized: "Session collector", bundle: .app), requirement: String(localized: "Log 25 sessions", bundle: .app), icon: "square.stack.3d.up.fill", unlocked: sessionCount >= 25, progress: progressText(String(sessionCount), String(localized: "25 sessions", bundle: .app))),
            .init(id: "marathon", title: String(localized: "Marathon", bundle: .app), requirement: String(localized: "Complete a 4-hour session", bundle: .app), icon: "figure.run", unlocked: longestSession >= 4 * 3600, progress: progressText(DurationText.compact(longestSession), String(localized: "4h", bundle: .app))),
            .init(id: "ultra", title: String(localized: "Ultra focus", bundle: .app), requirement: String(localized: "Complete an 8-hour session", bundle: .app), icon: "bolt.circle.fill", unlocked: longestSession >= 8 * 3600, progress: progressText(DurationText.compact(longestSession), String(localized: "8h", bundle: .app))),
            .init(id: "xp", title: String(localized: "XP engine", bundle: .app), requirement: String(localized: "Earn 10,000 XP", bundle: .app), icon: "star.fill", unlocked: xp >= 10_000, progress: progressText(String(xp), String(localized: "10,000 XP", bundle: .app))),
            // Mac'teki hedef rozetlerinin yerine sabit esikler: hedef
            // kullanicinin sectigi bir sayi oldugu icin istenildigi kadar
            // kucultulup rozet acilabiliyordu.
            .init(id: "fullday", title: String(localized: "Full day", bundle: .app), requirement: String(localized: "Work 8 hours in one day", bundle: .app), icon: "target", unlocked: fullDays >= 1, progress: String(localized: "\(fullDays) 8-hour days", bundle: .app)),
            .init(id: "longday", title: String(localized: "Long day", bundle: .app), requirement: String(localized: "Work 10 hours in one day", bundle: .app), icon: "arrow.up.right.circle.fill", unlocked: longDays >= 1, progress: String(localized: "\(longDays) 10-hour days", bundle: .app)),
            .init(id: "bigmonth", title: String(localized: "Hundred-hour month", bundle: .app), requirement: String(localized: "Work 100 hours in a calendar month", bundle: .app), icon: "calendar.circle.fill", unlocked: bigMonths >= 1, progress: String(localized: "\(bigMonths) 100-hour months", bundle: .app)),
            .init(id: "xp25", title: String(localized: "Quarter XP", bundle: .app), requirement: String(localized: "Earn 25,000 XP", bundle: .app), icon: "rosette", unlocked: xp >= 25_000, progress: progressText(String(xp), String(localized: "25,000 XP", bundle: .app))),
            .init(id: "active5", title: String(localized: "Getting steady", bundle: .app), requirement: String(localized: "Work on 5 different days", bundle: .app), icon: "calendar", unlocked: daily.count >= 5, progress: progressText(String(daily.count), String(localized: "5 active days", bundle: .app))),
            .init(id: "active25", title: String(localized: "Calendar regular", bundle: .app), requirement: String(localized: "Work on 25 different days", bundle: .app), icon: "calendar.badge.checkmark", unlocked: daily.count >= 25, progress: progressText(String(daily.count), String(localized: "25 active days", bundle: .app))),
            .init(id: "active100", title: String(localized: "Daily craft", bundle: .app), requirement: String(localized: "Work on 100 different days", bundle: .app), icon: "calendar.circle", unlocked: daily.count >= 100, progress: progressText(String(daily.count), String(localized: "100 active days", bundle: .app))),
            .init(id: "earlybird", title: String(localized: "Early bird", bundle: .app), requirement: String(localized: "Start 5 sessions before 08:00", bundle: .app), icon: "sunrise.fill", unlocked: earlyBirdSessions >= 5, progress: progressText(String(earlyBirdSessions), String(localized: "5 early starts", bundle: .app))),
            .init(id: "nightowl", title: String(localized: "Night owl", bundle: .app), requirement: String(localized: "Start 5 sessions after 22:00", bundle: .app), icon: "moon.stars.fill", unlocked: nightOwlSessions >= 5, progress: progressText(String(nightOwlSessions), String(localized: "5 late starts", bundle: .app))),
            .init(id: "weekend", title: String(localized: "Weekend warrior", bundle: .app), requirement: String(localized: "Work on 4 weekend days", bundle: .app), icon: "sun.max.fill", unlocked: weekendDays >= 4, progress: progressText(String(weekendDays), String(localized: "4 weekend days", bundle: .app))),
            .init(id: "sessions50", title: String(localized: "Deep archive", bundle: .app), requirement: String(localized: "Log 50 sessions", bundle: .app), icon: "books.vertical.fill", unlocked: sessionCount >= 50, progress: progressText(String(sessionCount), String(localized: "50 sessions", bundle: .app))),
            .init(id: "sessions100", title: String(localized: "Century sessions", bundle: .app), requirement: String(localized: "Log 100 sessions", bundle: .app), icon: "building.columns.fill", unlocked: sessionCount >= 100, progress: progressText(String(sessionCount), String(localized: "100 sessions", bundle: .app))),
            .init(id: "sessions200", title: String(localized: "Archive master", bundle: .app), requirement: String(localized: "Log 200 sessions", bundle: .app), icon: "square.stack.3d.up.fill", unlocked: sessionCount >= 200, progress: progressText(String(sessionCount), String(localized: "200 sessions", bundle: .app))),
            .init(id: "sessions500", title: String(localized: "Session institution", bundle: .app), requirement: String(localized: "Log 500 sessions", bundle: .app), icon: "building.2.crop.circle.fill", unlocked: sessionCount >= 500, progress: progressText(String(sessionCount), String(localized: "500 sessions", bundle: .app))),
            .init(id: "ultra12", title: String(localized: "Iron focus", bundle: .app), requirement: String(localized: "Complete a 12-hour session", bundle: .app), icon: "hourglass.bottomhalf.filled", unlocked: longestSession >= 12 * 3600, progress: progressText(DurationText.compact(longestSession), String(localized: "12h", bundle: .app))),
            .init(id: "ultra15", title: String(localized: "Deep dive", bundle: .app), requirement: String(localized: "Complete a 15-hour session", bundle: .app), icon: "water.waves", unlocked: longestSession >= 15 * 3600, progress: progressText(DurationText.compact(longestSession), String(localized: "15h", bundle: .app))),
            .init(id: "fullday7", title: String(localized: "Full week", bundle: .app), requirement: String(localized: "Work 8 hours on 7 days", bundle: .app), icon: "checkmark.seal.fill", unlocked: fullDays >= 7, progress: progressText(String(fullDays), String(localized: "7 8-hour days", bundle: .app))),
            .init(id: "fullday30", title: String(localized: "Full month", bundle: .app), requirement: String(localized: "Work 8 hours on 30 days", bundle: .app), icon: "target", unlocked: fullDays >= 30, progress: progressText(String(fullDays), String(localized: "30 8-hour days", bundle: .app))),
            .init(id: "bigmonth3", title: String(localized: "Quarter of hundreds", bundle: .app), requirement: String(localized: "Work 100 hours in 3 calendar months", bundle: .app), icon: "calendar.badge.checkmark", unlocked: bigMonths >= 3, progress: progressText(String(bigMonths), String(localized: "3 100-hour months", bundle: .app))),
            .init(id: "bigmonth12", title: String(localized: "Year of hundreds", bundle: .app), requirement: String(localized: "Work 100 hours in 12 calendar months", bundle: .app), icon: "calendar.badge.clock", unlocked: bigMonths >= 12, progress: progressText(String(bigMonths), String(localized: "12 100-hour months", bundle: .app))),
            .init(id: "streak90", title: String(localized: "Season streak", bundle: .app), requirement: String(localized: "Reach a 90-day streak", bundle: .app), icon: "flame.circle.fill", unlocked: longestStreak >= 90, progress: progressText(String(longestStreak), String(localized: "90 days", bundle: .app))),
            .init(id: "streak180", title: String(localized: "Half-year fire", bundle: .app), requirement: String(localized: "Reach a 180-day streak", bundle: .app), icon: "sun.max.fill", unlocked: longestStreak >= 180, progress: progressText(String(longestStreak), String(localized: "180 days", bundle: .app))),
            .init(id: "streak365", title: String(localized: "Year-round", bundle: .app), requirement: String(localized: "Reach a 365-day streak", bundle: .app), icon: "globe.americas.fill", unlocked: longestStreak >= 365, progress: progressText(String(longestStreak), String(localized: "365 days", bundle: .app))),
            .init(id: "active250", title: String(localized: "Always on", bundle: .app), requirement: String(localized: "Work on 250 different days", bundle: .app), icon: "calendar.badge.clock", unlocked: daily.count >= 250, progress: progressText(String(daily.count), String(localized: "250 active days", bundle: .app))),
            .init(id: "active500", title: String(localized: "Permanent practice", bundle: .app), requirement: String(localized: "Work on 500 different days", bundle: .app), icon: "calendar.circle.fill", unlocked: daily.count >= 500, progress: progressText(String(daily.count), String(localized: "500 active days", bundle: .app))),
            .init(id: "xp50", title: String(localized: "XP architect", bundle: .app), requirement: String(localized: "Earn 50,000 XP", bundle: .app), icon: "star.circle.fill", unlocked: xp >= 50_000, progress: progressText(String(xp), String(localized: "50,000 XP", bundle: .app))),
            .init(id: "xp100", title: String(localized: "XP legend", bundle: .app), requirement: String(localized: "Earn 100,000 XP", bundle: .app), icon: "sparkles", unlocked: xp >= 100_000, progress: progressText(String(xp), String(localized: "100,000 XP", bundle: .app)))
        ] + collectionBadges
    }

    private func progressText(_ current: String, _ target: String) -> String { current + " / " + target }
}
